### ISSUE TITLE
[ToDo] Use flask and get rid of the sleep

### ISSUE THREAD

**Issue by MiguelNdeCarvalho** [MiguelNdeCarvalho/speedtest-exporter#8]
- [x] Get rid of the arguments and get envs back (can't pass arguments when running with uwsgi)
- [x] Add landing page, like stated on Prometheus Documentation
- [x] Add **UWSGI** to the docker image and adapt start
- [x] Get rid of the sleep env
- [x] Add healthcheck
